### ISSUE TITLE
Not support the tn-ZA language in .Net container (Linux) 

### ISSUE THREAD

**Issue by Arunmali** [unicode-org/icu-docs#29]
FROM mcr.microsoft.com/dotnet/core/sdk:3.1 AS build
 
 No found the Setswana culture in above image
 
 Is there any way to support Tswana language in Linux container?

**Comment by markusicu** [comment]
Hi, this is the repo for ICU documentation. We don't manage bug reports on this repo.

I don't know what the process is for adding a locale to .Net. Please work with Microsoft on that.

For ICU and many other projects, locale data comes from the Unicode CLDR project: http://cldr.unicode.org/index/bug-reports#TOC-Adding-New-Locales

@jefgen @macchiati @srl295

**Comment by srl295** [comment]
@markusicu all agreed and I recommend disabling issues in this repo, checkbox @ https://github.com/unicode-org/icu-docs/settings
